spring:
  datasource:
    url: jdbc:h2:mem:product-catalog
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
