INSERT INTO products (name, description, price, category, stock, created_date, last_updated_date)
VALUES ('Apple iPhone 14', 'Latest smartphone with A15 Bionic chip and 128GB storage', 999.99, 'Electronics', 50, NOW(),
        NOW()),
       ('Samsung Galaxy S23', 'Flagship phone with Snapdragon 8 Gen 2 and Dynamic AMOLED screen', 899.99, 'Electronics',
        40, NOW(), NOW()),
       ('Sony WH-1000XM5 Headphones', 'Noise-canceling wireless headphones with 30-hour battery life', 399.99, 'Audio',
        60, NOW(), NOW()),
       ('Dell XPS 13 Laptop', 'Ultra-portable laptop with Intel Core i7 and 16GB RAM', 1299.99, 'Computers', 30, NOW(),
        NOW()),
       ('Logitech MX Master 3S', 'Ergonomic wireless mouse with fast scrolling and precision', 99.99, 'Accessories', 80,
        NOW(), NOW()),
       ('Nike Air Zoom Pegasus 40', 'Lightweight running shoes with responsive cushioning', 129.99, 'Footwear', 100,
        NOW(), NOW()),
       ('Adidas Ultraboost 22', 'High-performance running shoes for long-distance comfort', 179.99, 'Footwear', 70,
        NOW(), NOW()),
       ('Sony Bravia 55-inch 4K TV', '4K Ultra HD smart TV with HDR and Google TV integration', 699.99, 'Electronics',
        25, NOW(), NOW()),
       ('Asus ROG Strix Gaming Laptop', 'High-end gaming laptop with NVIDIA RTX 3080 GPU', 2299.99, 'Computers', 20,
        NOW(), NOW()),
       ('Bose QuietComfort 45', 'Over-ear headphones with industry-leading noise cancellation', 329.99, 'Audio', 45,
        NOW(), NOW()),
       ('Instant Pot Duo 7-in-1', 'Multi-cooker for pressure cooking, slow cooking, and more', 119.99,
        'Kitchen Appliances', 90, NOW(), NOW()),
       ('KitchenAid Stand Mixer', 'Iconic kitchen mixer with 5-quart stainless steel bowl', 449.99,
        'Kitchen Appliances', 35, NOW(), NOW()),
       ('Dyson V15 Detect Vacuum Cleaner', 'High-powered cordless vacuum with laser dust detection', 749.99,
        'Home Appliances', 15, NOW(), NOW()),
       ('Canon EOS R5 Camera', 'Full-frame mirrorless camera with 45MP resolution', 3899.99, 'Cameras', 10, NOW(),
        NOW()),
       ('GoPro HERO12 Black', 'Waterproof action camera with 5.3K video recording', 499.99, 'Cameras', 50, NOW(),
        NOW()),
       ('LEGO Star Wars Millennium Falcon', 'Detailed LEGO set with over 7500 pieces', 849.99, 'Toys', 20, NOW(),
        NOW()),
       ('Razer DeathAdder V3', 'Ergonomic gaming mouse with ultra-precise optical sensor', 69.99, 'Accessories', 120,
        NOW(), NOW()),
       ('Amazon Kindle Paperwhite', 'E-reader with 6.8-inch display and adjustable warm light', 139.99, 'Electronics',
        60, NOW(), NOW()),
       ('Herman Miller Aeron Chair', 'Ergonomic office chair with customizable lumbar support', 1499.99, 'Furniture',
        25, NOW(), NOW()),
       ('Philips Sonicare Toothbrush', 'Electric toothbrush with pressure sensor and timer', 99.99, 'Personal Care',
        200, NOW(), NOW()),
       ('Fujifilm Instax Mini 12', 'Instant camera for creating credit card-sized photos', 79.99, 'Cameras', 90, NOW(),
        NOW()),
       ('Microsoft Surface Pro 9', '2-in-1 detachable tablet with 13-inch touchscreen', 1199.99, 'Computers', 25, NOW(),
        NOW()),
       ('Yeti Rambler Tumbler', 'Stainless steel tumbler with MagSlider lid for hot and cold drinks', 39.99,
        'Kitchenware', 150, NOW(), NOW()),
       ('Anker PowerCore 20K', 'Portable power bank with 20000mAh capacity and fast charging', 59.99, 'Electronics',
        100, NOW(), NOW()),
       ('Patagonia Nano Puff Jacket', 'Lightweight insulated jacket with water-resistant finish', 229.99, 'Clothing',
        40, NOW(), NOW()),
       ('North Face Borealis Backpack', 'Versatile 28L backpack with multiple compartments', 99.99, 'Accessories', 80,
        NOW(), NOW()),
       ('Garmin Forerunner 265', 'Running smartwatch with GPS and heart rate monitoring', 499.99, 'Wearables', 35,
        NOW(), NOW()),
       ('Fitbit Versa 4', 'Smart fitness tracker with sleep and stress management features', 229.99, 'Wearables', 50,
        NOW(), NOW()),
       ('Cuisinart Air Fryer Toaster Oven', '12-in-1 appliance for baking, broiling, and air frying', 299.99,
        'Kitchen Appliances', 60, NOW(), NOW()),
       ('JBL Charge 5 Bluetooth Speaker', 'Portable waterproof speaker with 20-hour battery life', 179.99, 'Audio', 70,
        NOW(), NOW()),
       ('Google Nest Learning Thermostat', 'Smart thermostat with energy-saving features', 249.99, 'Smart Home', 30,
        NOW(), NOW()),
       ('Ring Video Doorbell 4', 'Wireless video doorbell with motion detection and HD video', 199.99, 'Smart Home', 45,
        NOW(), NOW()),
       ('Apple Watch Series 9', 'Smartwatch with always-on Retina display and health tracking', 399.99, 'Wearables', 50,
        NOW(), NOW()),
       ('DJI Mini 4 Pro Drone', 'Compact drone with 4K camera and obstacle avoidance', 799.99, 'Cameras', 15, NOW(),
        NOW()),
       ('Samsung 980 Pro SSD', '1TB PCIe 4.0 NVMe SSD for high-speed storage', 159.99, 'Computers', 100, NOW(), NOW()),
       ('HyperX Cloud II Gaming Headset', 'Comfortable gaming headset with 7.1 surround sound', 99.99, 'Audio', 75,
        NOW(), NOW()),
       ('Osprey Aether 65 Backpack', 'Premium hiking backpack with adjustable fit', 279.99, 'Outdoor', 30, NOW(),
        NOW()),
       ('Columbia Newton Ridge Boots', 'Durable hiking boots with waterproof construction', 139.99, 'Footwear', 50,
        NOW(), NOW()),
       ('Monopoly Board Game', 'Classic board game for family and friends', 29.99, 'Toys', 200, NOW(), NOW()),
       ('Sony PlayStation 5 Console', 'Next-gen gaming console with 4K gaming and SSD storage', 499.99, 'Electronics',
        15, NOW(), NOW()),
       ('Xbox Series X Console', 'High-performance gaming console with 1TB SSD', 499.99, 'Electronics', 20, NOW(),
        NOW()),
       ('HP Envy 6455e Printer', 'All-in-one printer with wireless and mobile printing features', 169.99,
        'Office Supplies', 40, NOW(), NOW()),
       ('Brother HL-L2370DW Printer', 'Compact monochrome laser printer with duplex printing', 199.99,
        'Office Supplies', 35, NOW(), NOW()),
       ('Corsair K95 RGB Keyboard', 'Mechanical gaming keyboard with customizable lighting', 199.99, 'Accessories', 25,
        NOW(), NOW()),
       ('Therm-a-Rest Sleeping Pad', 'Ultralight sleeping pad for camping and backpacking', 159.99, 'Outdoor', 50,
        NOW(), NOW()),
       ('Nintendo Switch OLED', 'Portable gaming console with vibrant 7-inch OLED screen', 349.99, 'Electronics', 30,
        NOW(), NOW()),
       ('Kindle Oasis E-Reader', 'Premium e-reader with adjustable warm light and 32GB storage', 249.99, 'Electronics',
        50, NOW(), NOW());
